### PR TITLE
Switch to using short import URL in README

### PR DESCRIPTION
**Pull request by koistya**
Ref yarnplugins/yarn-plugins#1

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
Nice, thanks. It should point to `latest` though not `master`. `master` is unstable, `latest` is not.

**Comment by koistya** [comment]
@eps1lon updated.

`https://yarnplugins.com/deduplicate` -> `latest`
`https://yarnplugins.com/deduplicate@latest` -> `latest`
`https://yarnplugins.com/deduplicate@master` -> `master`

I see that the latest versions of the official yarn plugins are published on the `master` branch at the same time with npm release:

```
https://github.com/yarnpkg/berry/raw/master/packages/plugin-<name>/bin/%40yarnpkg/plugin-<name>.js
```

**Comment by eps1lon** [comment]
The default should still point to `latest` which mirrors how npm installs would work. Is there a reason why you'd want unstable as the default?

**Comment by koistya** [comment]
@eps1lon just updated the default version to point to `latest` for `plugin-deduplicate`. An alternative approach would be using `master` as the default version, just don't push unstable bundles onto that branch (similarly to how @yarnpkg team doing it).

**Comment by eps1lon** [comment]
@koistya thanks!

**Pull request merged**
